### ISSUE TITLE
Need some help installing and setting up sccp in asterisk 

### ISSUE THREAD

**Issue by FoxMcCloud592** [marcelloceschia/chan-sccp-b#489]
Hello everyone, I am new to this and don't have much experience with working on command lines. I am trying to get a Cisco 7945 and a 8961 to register to a FreePBX server which is hosted on a VMware Virtual Machine, just so I can make snapshots and have access to the local disk easily.

I get the issue right at the start following these instructions https://github.com/Omid-Mohajerani/SCCP-Asterisk/wiki/Installing-CHAN-SCCP-in-Asterisk

when I cd /usr/src/ It just says that the directory does not exist

I am running Freepbx 13

I expect it to change directory to the issued one 

If someone could show me the commands for getting this to work, that would be fantastic. I am a dummy when it comes to linux and other OS's of the kind

(Screenshots which show reproduction steps and/or demonstrate the problem)
https://imgur.com/a/xup2yeT

**Comment by dkgroot** [comment]
@FoxMcCloud592 
The github url you are using looks to be outdated, and would lead to problems for sure. The first issue is that he is still using the master branch, which has not been updated for a long time (And has been changed so that it generated a warning when you try to compile it).

When running on FreePBX you can follow our [official wiki](https://github.com/chan-sccp/chan-sccp/wiki/FreePBX).

Step one:
```
cd /usr/src
git clone https://github.com/chan-sccp/chan-sccp
cd chan-sccp
./configure
make -j4
make install
```
Note the first line is `cd /usr/src` not `cd usr/src` as you showed in your screenshot.

Also note that in the Omid-Mohajerani url he/she suggests using `vim` to edit files. As a user not familiar to linux, you will have problems using vim. It would be better to use a simple editor like `nano` instead.

When you have done the compilation step and the module.conf step, you should look for the FreePBX plugin module called `sccp_manager` and install it, it will take care of the rest of the installation like setting up sccp.conf and the database tables etc.

Just follow: https://github.com/chan-sccp/chan-sccp/wiki/FreePBX_Installation and you should be ok, and you get the sccp_manager plugin plus chan-sccp installed. If you still run into an issue while trying to follow this process then please respond to this issue report and we can see how to solve it and update the wiki if necessary.

(Maybe we should tell this Omid person, to update or take down his wiki.

**Comment by FoxMcCloud592** [comment]
Alright, looks like I got somewhere. I got until step 5.build a sccp.conf config file (look in the conf/ directory for examples). For example you could use the freepbx examples by doing this:

cp conf/sccp.conf.freepbx /etc/asterisk/sccp.conf

mv /etc/asterisk/sccp_extensions.conf /etc/asterisk/sccp_extensions.conf.bak   ; sccp_manager uses realtimedb for line entries
mv /etc/asterisk/sccp_hardware.conf /etc/asterisk/sccp_hardware.conf.bak       ; sccp_manager uses realtimedb for device entries

Here is what happens when I put these commands in https://imgur.com/a/ZvMT1Fc

**Comment by dkgroot** [comment]
for that command to work, you need to be still in the /usr/src/chan-sccp/ directory
```
cd /usr/src/chan-sccp
cp conf/sccp.conf.freepbx /etc/asterisk/sccp.conf
```
The mv command is not required, as you never had chan-sccp installed before.
You should not have to alter the resulting /etc/asterisk/sccp.conf, as far as in know, but you might want to have a quick look through it using `nano /etc/asterisk/sccp.conf`

Also for the future, if the command line is not really your thing, you might want to install something like midnight command or other shell tool, to help you out a little:
```
yum install mc
```
and maybe have a look around for a simple beginners course on using linux, just to feel a little more at home on your new machine, even if you don't need it much, it might make you a little more confident.

**Comment by FoxMcCloud592** [comment]
We took a short class on Linux essentials when I was taking Cisco Academy my senior year. But I really didn't want to do anything with Linux when I was taking the class because they were also showing router and switch configurations. Honestly, that was far more interesting. Than learning Linux. I think I'm just going to suck it up and learn the command line interface. Thanks for helping and I'll play around and read some more about SCCP on here and I'll write back for anymore questions

**Comment by FoxMcCloud592** [comment]
So with all this installed, how do I register the phone with the newly installed SCCP? It has an IP address from DHCP on my router.

**Comment by dkgroot** [comment]
Ok good

Checklist:
1. [ ] is a tftp server installed (make sure it is the one that comes with FreePBX and expect by sccp_manager, use `yum` to check).
2. [ ] is xinetd or inetd installed (normally one should already be installed, use `yum` to check)
3. [ ] have you setup TFTP server to provision the phones (AFAIK sccp_manager does part of this for you
4. [ ] have you setup DHCP to point to your TFTP Server (Check that this is the case)
5. [ ] check /var/log/messages or /var/log/syslog to see if a phone is retrieving it's SEPxxxxxx.cnf.xml fi le
6. [ ] check the phone settings to see if the ip-address is in the range
7. [ ] check the phone settings to make sure that the tftp is correct
8. [ ] check the phone settings to check the CM (Call Manager) Address
9. [ ] look at the phone web interface and read the console log, to see what it is doing

**Comment by FoxMcCloud592** [comment]
Ah, I see. I have DHCP on my router but no way to point it to my PBX. I
have a copy of windows server, so I can install tftp, DHCP clients on the
computer. I will need some help with all thoes things on the check list. I
know it's a lot to ask for wince you have been so helpful already, but
maybe a voice chat would be the easiest way to get help with this. Also,
I'll have to load a new SCCP firmware on the phone since it has passwords
on it.

**Comment by dkgroot** [comment]
For now you can set the tftp-server ip-address manually in the phone-settings-network page. You switch to admin mode on the phone using '**#', then you switch 'alternate tftp server':on and go to the field above to enter the ip-address of the tftp server. If you need a password you don't know, you are out of luck.

Do have a look at our wiki for example [Change-firmware-from-SIP-to-SCCP](https://github.com/chan-sccp/chan-sccp/wiki/Change-firmware-from-SIP-to-SCCP) and [Factory-Reset](https://github.com/chan-sccp/chan-sccp/wiki/Factory-Reset). **Mind you before doing either of these means you have to have a working DHCP/TFTP combination to work, this will not work with 'manually set tftp server' !!**.

Please use the tftp-server of the PBX, because it is automatically setup/configured by sccp_manager. I don't know what router you have or what options you can set on this router (check it's manual). You can use any DHCP server to point the phone at it's tftp server address. You need to be able to add/set 'custom dhcp options' though.

We do have a chat site: https://gitter.im/chan-sccp/chan-sccp so visit us there to speed up the process a little.

**Comment by FoxMcCloud592** [comment]
Yes, unfortunately I'll have to upload a new config to the phone, it has a
password on it. Or is there an easier way to get rid of the password?

**Comment by dkgroot** [comment]
Nope factory reset is the only way to go, in this case. If need be you can setup a local dhcp/tftp combo on your laptop and connect the phone directly to it, **make sure it boots and get's firmware/config from it**, and when you are absolutely sure it does, perform the factory-reset. You will have to have the firmware for your specific phone ready on your laptop in that case.

**Comment by FoxMcCloud592** [comment]
Okay, ill write back when I get home. Thanks.

**Comment by dkgroot** [comment]
You can run DHCP / TFTP Server on the PBX side by side if that is easier. But setting up two DHCP side by side next to a 'hardware' router is going to be difficult.

**Comment by dkgroot** [comment]
@davidded / @ojaksch 
One of you might be able to help out better regarding windows DHCP/TFTP then i do. I have not used Windows in 15-20 years :-)

@ FoxMcCloud592 We are here to develop & support chan-sccp channel driver. Not help you setup all kinds of other servers/services etc. We will help with other stuff to some extend, but cannot be expected to go above and beyond.

**Comment by FoxMcCloud592** [comment]
Ah then lets use something that we all understand. Would Tftpd64 be a
familiar thing?
So my gateway address is 10.0.161.223
My host is 10.0.161.134
And the phone address is 10.0.161.118
Im going off to download the SCCP firmware. How do I upload it to the phone
with tftpd64

**Comment by FoxMcCloud592** [comment]
Or lets run the one on the PBX

**Comment by dkgroot** [comment]
Skim through this page, and read the DHCP/TFTP ones. They explain in detail how the process works, and gives serveral examples of possible setups. LInux has multiple versions of DHCP and TFTP services so you need to pick the one that fits your needs/distro/preference/etc. Regarding DHCP it even includes an (older) example for Windows how to add 150/66 dhcp custom options to redirect the client to the correct tftp server.

> Or lets run the one on the PBX.

As you have not told me/us the Linux Distro you are using i am not able to help much, saying FreePBX 13 does not tell me anything.

**Comment by FoxMcCloud592** [comment]
Here is what this release of FreePbx reports as its version.
https://imgur.com/a/ReHne1x . I understand that getting your assistance is
a privilege, therefore I'd completely understand If you no longer would
like to walk me through the steps. My inexperienced is probably a tad
annoying =)

**Comment by dkgroot** [comment]
@FoxMcCloud592 Please join the [chat](https://gitter.im/chan-sccp/chan-sccp) to speed up the proces. You have not tired me out just yet :-) ! Getting a little help from some other people is not a shame. Have you had time to read the pages i mentioned, to have some background information about what is required for the phones to get the appropriate tftp server information ?

You are lucky that /proc/version contains the OS tag in this case :-). So you are running an old/outdated version of Centos(6).

On the chat the best person to ask for a little help might be Alexander (@PhantomVl) who developed the sccp_manager plugin. I think he uses Centos as well and knows what dhcp/tftp services to use there.

**Comment by FoxMcCloud592** [comment]
Sure, see you guys there!

**Comment by FoxMcCloud592** [comment]
I'll come by, let me read this some more and come back to you guys. Thank
you very much

**Comment by dkgroot** [comment]
Switched to chat
