### ISSUE TITLE
Freepbx 15 update module issue

### ISSUE THREAD

**Issue by vregal** [marcelloceschia/chan-sccp-b#490]
Following Quick Installation guide, point 4b, no way to add modules chan_skinny.so and chan_sccp.so

**Reproduction Steps:**

1. Freepbx 15 web gui, Admin->Asterisk Modules, under Excluded Modules
2. Try to add chan_skinny.so
3. system responds with message: "Call to a member function noload() on null File:/var/www/html/admin/modules/core/Core.class.php:486

**Comment by dkgroot** [comment]
@vregal 
If i interpret that response correctly, than chan_skinny.so is not available on that system, which is fine. Because we want to prevent it from being loaded. So not there would have the same effect.

**Comment by nickvsh** [comment]
> chan_skinny.so is not available on that system

In fact, it is.
![image](https://user-images.githubusercontent.com/22931670/68771832-6b34ad80-0631-11ea-9c19-a32be4d0fcee.png)

I suppose it's a bug of FreePBX 15 (on v14 was OK), because it's now working even on modules that was already there like `chan_alsa.so`, or anything like `app_test.so, chan_sip.so, app_dial `etc. You can't **Add** or **Delete** anything from **Excluded/Loaded/Preloaded** list...

I used a workaround: `rm /usr/lib64/asterisk/modules/chan_skinny.so` + restart asterisk.
Luckily, there is **autoload=yes** in  autogenerated /etc/asterisk/modules.conf, so no need to add **chan_sccp.so** to the list from GUI.

![image](https://user-images.githubusercontent.com/22931670/68773226-db443300-0633-11ea-9ba4-be8cbb63ec83.png)

![image](https://user-images.githubusercontent.com/22931670/68773336-0fb7ef00-0634-11ea-9199-62aa456ca0b3.png)

![image](https://user-images.githubusercontent.com/22931670/68772670-db8ffe80-0632-11ea-8497-7a89c4551b42.png)

**Comment by dkgroot** [comment]
@nickvsh  Thanks for reporting back to this thread on this matter !
Looks like some errors in processing the page are occuring, has anyone checked if these were reported to the FreePBX developers ?
Should we update the wiki, or just wait until it is fixed upstream ? Instead of deleting the skinny module, you can also just edit /etc/asterisk/module.conf of course ?

**Comment by Idkwhattocallme** [comment]
is there a workaround to this?

**Comment by dkgroot** [comment]
@Idkwhattocallme 
Just edit /etc/asterisk/modules.conf manually, that should work. Or delete the chan_skinny.so module as @nickvsh mentioned (See above)

**Comment by nickvsh** [comment]
@vregal @Idkwhattocallme @dkgroot 
I don't recommend editing **/etc/asterisk/modules.conf**, because it is auto-generated by FreePBX.
Any manual modifications will be erased after first "Apply" in FreePBX GUI!

Updated FreePBX "core" module was released to fix this issue (27/Sep/2019)
But it's in the so called "edge" truck.

More detailes here
https://issues.freepbx.org/browse/FREEPBX-20599?focusedCommentId=167779&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-167779

> This module will be pushed to the Stable repo as soon as it meets the criteria for transition.

You need to enable "edge" repo to see this version from GUI (Module Admin).

Or simply run this command to upgrade core module from "edge" truck/repository.

`fwconsole ma --edge upgrade core`

![image](https://user-images.githubusercontent.com/22931670/69559187-25bd9c00-0fb2-11ea-94ee-d7666589f883.png)

![image](https://user-images.githubusercontent.com/22931670/69559790-44706280-0fb3-11ea-8e45-08575808ca37.png)

Chan_skinny.so is excluded

![image](https://user-images.githubusercontent.com/22931670/69559115-0757a080-0fb2-11ea-8f7d-f634e92a350a.png)

![image](https://user-images.githubusercontent.com/22931670/69559869-6b2e9900-0fb3-11ea-83b4-b1e766874265.png)

> Should we update the wiki, or just wait until it is fixed upstream ?
 
I think we should update wiki with information, that "Asterisk  Modules" bug is relevant until **core module** version **at least** **15.0.9.47** will be in stable repo.

**Comment by dkgroot** [comment]
@nickvsh As you have experience with this, would you mind editing out freepbx wiki pages ? Thanks
@vregal Does this solve your issue and can we close this issue report ?

**Comment by nickvsh** [comment]
> would you mind editing out freepbx wiki pages ? Thanks

Done.

**Comment by dkgroot** [comment]
@nickvsh Thank you !! Looks good to me :-) !

**Comment by dkgroot** [comment]
@vregal Closing this issue report for now. If there are still problems, reopen the issue report.
