### ISSUE TITLE
Some calls from queue have to be picked up twice

### ISSUE THREAD

**Issue by Zw1d** [marcelloceschia/chan-sccp-b#519]
At first I wanted to make it clear that I think this is quite likely NOT chan-sccp fault! However I wanted to ask advice on how I could diagnose it. Any hints would be much appreciated!

**Reproduction Steps:**

1. Call external number
2. I don't know, get lucky I guess

**chan-sccp version:** Skinny Client Control Protocol (SCCP). Release: 4.3.2 develop - 33da090

**asterisk version:** Asterisk 16.6.1

**Expected behavior:**

Call get connected / picked up on the first try.

**Observed behavior:**
This happens maybe in 1 out of 5 calls.
Incoming calls get placed in queue with 5 sccp agents (all local). 
Extensions ring, then one gets picked up, but caller doesn't get connected.
The caller that had this issue said he didn't hear even the queue music (like he wasn't "fully" placed in queue, since the queue did ring it's agents?), just silence, then got disconnected (I assume he gets disconnected when the agent picks up). He called again, got connected without issues.

**Addition / Optional Information:**
- Problem started happening recently, didn't happen in an older version of Chan-SCCP: [No]
- Problem can be reliably reproduced, doesn't happen randomly: [No]
- Platform:
  - ARMv7 Processor rev 4 (v7l)
  - RasPBX
  - Raspbian GNU/Linux 10

**Comment by dkgroot** [comment]
@Zw1d 

We did change the 'call answer' logic quite substantially recently. So to confirm if the issue is caused by this somewhat recent change, can you see 8faf32 if has the same effect (`git checkout 8faf32`) ? We have done quite a bit of testing with this new "call answer" logic, but in retrospect we might have skipped over the use of "Local Channels" and "optimizing out". If we can establish that the issue started after march 8th (revision: 8faf32), we would know what to focus our attention on during testing.

For me to reproduce the issue, are you using local channels in the queue and are they set to "optimize" out or not. To ask the question a different way, can you show me a queue definition to replicate your current situation.

Can you set `sccp debug core, device, line, channel, indicate, pbx, rtp` during testing (before/after 8faf32) and show the results. There might be something significant in the debug trace showing the reason for the call not being 'answered' but  not 'established'/'coming up'.

(Also there have been a couple of commits since 33da090, have you tried with latest before issuing a bug report ? (Not saying it should be fixed already)).

**Comment by Zw1d** [comment]
Since the issue can be tested only on my production system I will start with the latest version and report back.
But do you really think this could be sccp-chan module fault? Why isn't caller hearing music from the queue?
What do you mean by 
> are you using local channels in the queue and are they set to "optimize" out or not

Channels are local to that queue.

**Comment by dkgroot** [comment]
It would help if you show me the queue definition on the CLI (`queue show [queuename]`), so i can try an reproduce the issue. Also setting the debug level as requested should make it possible to analyze what is going on, and potentially point the finger at the case, it being chan_sccp or not.

> are you using local channels in the queue and are they set to "optimize" out or not

See: https://wiki.asterisk.org/wiki/display/AST/Local+Channel

Note:
AstDevBox*CLI> queue show Queue1 
Queue1 has 0 calls (max unlimited) in 'rrmemory' strategy (0s holdtime, 0s talktime), W:0, C:0, A:0, SL:0.0%, SL2:0.0% within 0s
   Members: 
      SCCP/98031 (ringinuse enabled) (Unavailable) has taken no calls yet
      SCCP/98041 (ringinuse enabled) (Unavailable) has taken no calls yet
      SCCP/98011 (ringinuse enabled) (Unavailable) has taken no calls yet
   No Callers

AstDevBox*CLI> queue show SCCP/Queue2
Queue1 has 0 calls (max unlimited) in 'rrmemory' strategy (0s holdtime, 0s talktime), W:0, C:0, A:0, SL:0.0%, SL2:0.0% within 0s
   Members: 
      Local/98031 (ringinuse enabled) (Unavailable) has taken no calls yet
      Local/98041 (ringinuse enabled) (Unavailable) has taken no calls yet
      Local/98011 (ringinuse enabled) (Unavailable) has taken no calls yet
   No Callers

The later is a queue using so called "Local" Channels which is a temporary stand-in for the actualy destination, The actual destination is reached by doing through the dialplan again. With a non Local channel, the destination would be Dialed immediately (Dial()).
Optimizing out means that the "Local" Channel vanishing after it is answered, using a so called masquerade to switch channel innards. 
The "Local" channel stand-in does make the handling of calls a lot more complicated, but also a lot more flexible.

You not being aware of so called "Local" channels, might mean you are using some kind of GUI / frontend that shields you from 'reality' :-)

**Comment by Zw1d** [comment]
Okay here's my queue:
```
o*CLI> queue show 4099
4099 has 0 calls (max unlimited) in 'ringall' strategy (23s holdtime, 35s talktime), W:0, C:2, A:0, SL:100.0%, SL2:100.0% within 60s
   Members:
      Room1 (Local/4105@from-queue/n from hint:4105@ext-local) (ringinuse enabled) (Not in use) has taken 1 calls (last was 52 secs ago)
      Person1 (Local/4004@from-queue/n from hint:4004@ext-local) (ringinuse enabled) (Not in use) has taken no calls yet
      Person2 (Local/4001@from-queue/n from hint:4001@ext-local) (ringinuse enabled) (Not in use) has taken no calls yet
      Person3 (Local/4002@from-queue/n from hint:4002@ext-local) (ringinuse enabled) (Not in use) has taken 1 calls (last was 3 secs ago)
      Person4 (Local/4003@from-queue/n from hint:4003@ext-local) (ringinuse enabled) (Not in use) has taken no calls yet
   No Callers

o*CLI>
```

Yeah I use FreePBX, asterisk wasn't simple enough on the first glance to dive right in, but I'm slowly getting there.

**Comment by dkgroot** [comment]
Ok so we are using "Local" channels which is fine. And that means i should run a couple of tests, to see if i can reproduce the issue on `vanilla` asterisk you are seeing. Being able to reproduce the problem makes it much easier to fix any potential issue.

- Note: If i cannot reproduce the issue on vanilla asterisk, it doesn't mean the problem does not exist, or/and is not produced by chan_sccp.
- Testing with the 8faf32 revision, would still help (I guess we have to wait for some downtime).
- Also it would help if you send the CLI debug output from your current system (when it is and isn't happening) so we can find the difference (You should be able to do that at this moment). As we are using Local channels, the dialplan output is also important, so please set (before running both tests)
  - `core set debug 1`
  - `core set verbose 5`
  - `sccp debug core, device, line, channel, indicate, pbx, rtp`

You can upload the debug output to some pastebin (for example https://0x0.st) website and attach a link to it, in this issue thread. (Or use the github drag/drop solution).

**Comment by Zw1d** [comment]
All right, I will try to do that. So far I can confirm that the issue just occured on:
`Skinny Client Control Protocol (SCCP). Release: 4.3.2 develop - 81f140a`
I will try to catch logs from it.

**Comment by dkgroot** [comment]
I just set up a Queue on my vanilla asterisk and on a remote FreePBX machine and ran some tests with both (running latest chan_sccp). So far i have not seen what you are reporting. You mentioned "luck" which is not great when trying to reproduce the issue, that might indicate we have a timing issue on our hands (different hardware will react very differently in that scenario).

Note: please set `core set debug off` instead of `1` (but keep `core set verbose 5`), because i noticed that is generating a lot more unnecessary output, that makes reading the output harder.

**Comment by Zw1d** [comment]
Okay, I will change the debug. I think I will just hunt for that buggy call and try to pin down the logs.

**Comment by Zw1d** [comment]
A week ago I have changed register string in my primary sip provider. I removed (I think) timeout \~90 from the end of the string. So changed from:
1234@host.com:password:1234@0.0.0.0~90
to:
1234@host.com:password:1234@0.0.0.0
And since then haven't experienced that particular issue, so hopefully that was it.

**Comment by dkgroot** [comment]
@Zw1d Thanks for reporting back and closing the issue. If the issue does pop up do open it up again.
